os: Visual Studio 2017
version: 2.2.{build}

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip

branches:
  only:
    - master

cache:
  - src\Website\node_modules
  - '%APPDATA%\npm\node_modules'
  - '%APPDATA%\npm-cache'

install:
  - ps: npm install --global npm

build_script:
  - ps: .\Build.ps1

after_build:
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "artifacts\coverage.cobertura.xml"

artifacts:
  - path: artifacts\publish
  - path: artifacts\coverage*.xml

nuget:
  disable_publish_on_pr: true

skip_tags: false
test: off
